### ISSUE TITLE
Come help out with mgmtconfig?

### ISSUE THREAD

**Issue by purpleidea** [ChrisMcKenzie/preflight#5]
Saw this learning exercise of yours. In case you'd prefer to come help out with mgmt, please feel free to get involved. https://github.com/purpleidea/mgmt/ We're hanging out in #mgmtconfig on Freenode too. I'm purpleidea.

**Comment by ChrisMcKenzie** [comment]
Thank you for the invite I would love to help out! I'll take a look at the issues and see if there is something I can jump on!
